# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sesquimathematical musings
email: mkliegl@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on mathematics, data science, machine learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mkliegl.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  github

# Build settings
markdown: kramdown
