# Site settings
title: Markus Kliegl's Blog
email: mkliegl@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  Mathematics, data science, machine learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mkliegl.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  mkliegl

# Build settings
markdown: kramdown
